# Generated by Django 3.2.7 on 2022-07-29 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('employer', '0003_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(choices=[('it', 'توسعه نرم افزار و برنامه نویسی')], on_delete=django.db.models.deletion.CASCADE, to='portal.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 17, 44, 59, 686028)),
        ),
    ]
