# Generated by Django 3.2.7 on 2022-08-18 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('employer', '0006_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 11, 18, 35, 194297)),
        ),
    ]
